name: ci-image

on:
  push:
    branches:
      - main
    paths:
      - "docker/Dockerfile"

jobs:
  ci-image:
    name: "Create CI Image"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: true
          tags: ghcr.io/${{ github.repository }}/ci:latest
