name: build-ci-image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create-ci-image:
    name: "Create CI Image"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: true
          tags: ghcr.io/${{ github.repository }}/ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
