name: main

on:
  push:
    branches:
      - main

jobs:
  check-for-ci-image-changes:
    runs-on: ubuntu-latest
    outputs:
      need-to-build-image: ${{ steps.filter.outputs.dockerfile-changed }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            dockerfile-changed:
              - 'docker/Dockerfile'
  create-ci-image:
    name: "Create CI Image"
    runs-on: "ubuntu-latest"
    needs: check-for-ci-image-changes
    if: needs.check-for-ci-image-changes.outputs.need-to-build-image == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: true
          tags: ghcr.io/${{ github.repository }}/ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  tag-pre-release:
    name: "Tag Pre-Release"
    runs-on: "ubuntu-latest"
    needs: create-ci-image
    container: "ghcr.io/${{ github.repository }}/ci:latest"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Build website & ebook
        run: make all
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Pre-Release"
          files: |
            build/engineering-culture-at-celebrate.*
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/website
