name: main

on:
  push:
    branches:
      - main

jobs:
  check-for-ci-image-changes:
    runs-on: ubuntu-latest
    outputs:
      need-to-build-image: ${{ steps.filter.outputs.dockerfile-changed }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            dockerfile-changed:
              - 'docker/Dockerfile'
  create-ci-image:
    name: "Create CI Image"
    needs: check-for-ci-image-changes
    if: needs.check-for-ci-image-changes.outputs.need-to-build-image == 'true'
    uses: ./.github/workflows/ci-image.yml
  tag-pre-release:
    name: "Tag Pre-Release"
    runs-on: "ubuntu-latest"
    needs: create-ci-image
    if: ${{ always() }}
    container: "ghcr.io/${{ github.repository }}/ci:latest"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Build website & ebooks
        run: make all

